version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  yt-archive-sync:
    docker:
      - image: cimg/python:3.9

    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run main app
          command: |
                ia configure --username="$ARCHIVE_USER_EMAIL" --password="$ARCHIVE_PASSWORD" > /dev/null 2>&1 &&
                python create_collection.py --hide > /dev/null 2>&1 &&
                python archive_yt_channel.py --hide > /dev/null 2>&1

workflows:
  sync:
    jobs:
      - yt-archive-sync
